# Generated by Django 2.1.5 on 2019-01-18 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0012_family_family_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
