# Generated by Django 2.1.5 on 2019-02-01 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_budget', '0013_auto_20190118_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='expensesplan',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='familymembers',
            name='family_member_id',
        ),
        migrations.AddField(
            model_name='categories',
            name='type_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expensesplan',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowoffunds',
            name='family_member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
