# Generated by Django 2.1.5 on 2019-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0015_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passport_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
