# Generated by Django 2.1.5 on 2019-02-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0017_delete_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowoffunds',
            name='family_member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='family_budget.FamilyMembers'),
        ),
    ]
