# Generated by Django 2.1.5 on 2019-02-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0019_flowoffunds_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymembers',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='flowoffunds',
            name='family_member_id',
        ),
        migrations.DeleteModel(
            name='FamilyMembers',
        ),
    ]
