# Generated by Django 2.1.5 on 2019-02-09 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0020_auto_20190209_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowoffunds',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 16, 59, 49, 605033)),
        ),
    ]
