# Generated by Django 2.1.5 on 2019-02-12 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0022_auto_20190209_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowoffunds',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
