# Generated by Django 2.1.5 on 2019-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0025_auto_20190218_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type_id',
            field=models.IntegerField(),
        ),
    ]
