# Generated by Django 2.1.5 on 2019-02-18 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_budget', '0027_auto_20190218_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro', models.FloatField(default=0)),
                ('dollars', models.FloatField(default=0)),
                ('days_before_salary', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
