# Generated by Django 2.1.5 on 2019-01-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('sum_plan', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member_id', models.IntegerField(blank=True)),
                ('family_user_name', models.CharField(max_length=100)),
                ('user_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlowOfFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_it_expense', models.BooleanField(default=True)),
                ('family_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Family')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='flowoffunds',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Users'),
        ),
        migrations.AddField(
            model_name='family',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Users'),
        ),
        migrations.AddField(
            model_name='expensesplan',
            name='family_member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Family'),
        ),
        migrations.AddField(
            model_name='expensesplan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Users'),
        ),
    ]
