# Generated by Django 2.1.5 on 2019-01-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member_id', models.IntegerField(blank=True)),
                ('family_member_name', models.CharField(max_length=100)),
                ('family_member_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='family',
            old_name='family_user_name',
            new_name='family_name',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='expensesplan',
            name='family_member_id',
        ),
        migrations.RemoveField(
            model_name='expensesplan',
            name='type',
        ),
        migrations.RemoveField(
            model_name='expensesplan',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='family_member_id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='user_description',
        ),
        migrations.RemoveField(
            model_name='family',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='flowoffunds',
            name='user_id',
        ),
        migrations.AddField(
            model_name='categories',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Family'),
        ),
        migrations.AddField(
            model_name='expensesplan',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Family'),
        ),
        migrations.AddField(
            model_name='expensesplan',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Categories'),
        ),
        migrations.AddField(
            model_name='family',
            name='password_hash',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='flowoffunds',
            name='family_member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Family'),
        ),
        migrations.AlterField(
            model_name='flowoffunds',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Categories'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='familymembers',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_django_project.Family'),
        ),
    ]
