# Generated by Django 2.1.5 on 2019-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0002_auto_20190110_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_id',
            field=models.IntegerField(default=1),
        ),
    ]
