# Generated by Django 2.1.5 on 2019-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0010_remove_family_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_id',
            field=models.IntegerField(default=1),
        ),
    ]
