# Generated by Django 2.1.5 on 2019-02-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0016_auto_20190205_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
