# Generated by Django 2.1.5 on 2019-02-06 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_django_project', '0018_auto_20190206_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowoffunds',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
