# Generated by Django 2.1.5 on 2019-02-09 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0021_auto_20190209_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowoffunds',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 9)),
        ),
    ]
