# Generated by Django 2.1.5 on 2019-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0023_auto_20190212_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='flowoffunds',
            name='is_it_expense',
        ),
        migrations.AddField(
            model_name='categories',
            name='is_it_expense',
            field=models.BooleanField(default=True),
        ),
    ]
