# Generated by Django 2.1.5 on 2019-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0026_auto_20190218_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type_id',
            field=models.IntegerField(default=1),
        ),
    ]
