# Generated by Django 2.1.5 on 2019-02-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_django_project', '0028_savingmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingmoney',
            old_name='days_before_salary',
            new_name='salary_day',
        ),
    ]
